language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://telegacom.pact.dius.com.au
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "yv6R5xIDVW/W5e3NEH6XUAYKF9yKOuIFRvslKxHO0iEDAJCeZE+gxc70aU2FSm/B9zNR1YkYXu3D/y3oUnRhYtNbHJR/1wmU236y9Y7eDRxn8YYxhY4PCn/NGphRau+jUf2K54YMztRsuWx8pAhjMf4n1aMjcqfbYpzexEt1rLDaB/URGvKxVXx5QH7cQmEgmb5jJWJ3y/B09p3jxwI4baJlgbTgn3yiuZ5B6tvsTqPJOG2V3i0p+LQys00LI2hoTgOGV3f3yFaZavmv3kuojx/5kUVEKkKLfJvrkqjgjtAeVSwRHHTVB7RErjsBDlshbROwewmLJuHMqOu5iDwv0zV1iZcyeBBhGBocPvA2ZlvUWOxcs+9DxexTiECmXFAFVkK1KDSsEiomjwehk3R6eR6yd+2uORyvRT60ftZ+dDHJyCn2kE95N39yVdespjJKaC0f/0pq31L6+JfAVSAunigYkKfPZnn59j172FZ0yFFSenicJHFjeg1XKaSGQosUshfRkz1D9IS2CcxnlE09Es/i26sF4vm/I7+EUwElgZLCJ1kPAB4DLbZAynydH/BX/+FAxhteTKH1c5Y1VGpehunwqP04eWM2cjc2SjCg14b1nhMmTjwFRpXcbrJty8jxc6NQH9HwUHi/0p4k5sXGIEMQVvU/sBO9b6GSzyH5cBA="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
