language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://telegacom.pact.dius.com.au
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "ltQxkCVKGoAO6/1GlTsmzcjwZfecwqUQbc4S7+AwFd5kJcHjZrtGIdqEwpkUBeF0WWnOwzrC24jZusfP5Ebp9nMsX3hELFAo8ADCRkxMHpYTLTdTbTVN2MdRumgo/wpooPEsj8550B8i/N7wbg96zo/ZqPKgObkngBHSZfnUJlEMQZ9aF7cy+METys2PaQTQYAjrkNM6El4wyrQNSfwAPP8VuVwfLoFnh+sY9wiExvzw07760LiOQJfgcP2LFHmrchEc0U5yA4HZZB2a1Dxpc1ETI8TZ9EQW41EQ3inkgI8EPkD8PpoR+uznonYyOIFtkVL3vTwmhd7Up2r5jeHyUYmLtv7pfATAegkW7qt3gdHxt2cAdD2ewNwigp0Fo27vTJdzIwSjY7YR33eCK0nm6jnFSRj8Ck/Ik6S/Ip+CeQqB7wKLlTh4foExI8ILsOH/WmDhmSHvAzv2IZNeTLaNOGqJyvgll4mstkBJh63a9o1HvFYoJR7W89OQPNs2m7SFUfRCOKryXGVOmunCKqcHuqDtV3QYpVS3QtHRCzTytFX9ES6lVW1g4ypWkIfZv2CNtJ4evZgUK4cVdGFskCIJwHWqDAobkQgFAF8biRHW4RYJ1XXEHchqdIqD6jj4XK5SHBUB9F+eR7sjQwpQlmCAehs6c7ocuUuRimYTjHc4aws="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
